const realms = [
  {
    number: 1,
    title: "The Realm of Laughter",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
    caption: "Where your giggles echo like magic.",
  },
  {
    number: 2,
    title: "The Realm of Serendipity",
    caption: "Where sweet accidents become destiny.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 3,
    title: "The Realm of Fire",
    caption: "Your passion, your rage, your warmth.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 4,
    title: "The Realm of Dreams",
    caption: "Where your wildest hopes live free.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 5,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 6,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 7,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 8,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 9,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 10,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 11,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 12,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 13,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 14,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 15,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 16,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 17,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 18,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 19,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 20,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 21,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 22,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/images/real/realm1.jpg",
    audio: "/audio/realm1.mp3",
  },
  {
    number: 23,
    message: "Happy 23rd, my universe! 💖🎉",
    image: "/images/real/23.png",
    audio: "/audio/23.mp3",
    isSpecial: true,
  },
];

export default realms;
