const realms = [
  {
    number: 1,
    title: "The Realm of Laughter",
    image: "/assets/images/1.png",
    audio: "/assets/audio/audio1.mp3",
    caption: "Where your giggles echo like magic.",
  },
  {
    number: 2,
    title: "The Realm of Serendipity",
    caption: "Where sweet accidents become destiny.",
    image: "/assets/images/2.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 3,
    title: "The Realm of Fire",
    caption: "Your passion, your rage, your warmth.",
    image: "/assets/images/3.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 4,
    title: "The Realm of Dreams",
    caption: "Where your wildest hopes live free.",
    image: "/assets/images/4.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 5,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/5.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 6,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/6.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 7,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/7.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 8,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/8.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 9,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/9.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 10,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/10.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 11,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/11.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 12,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/12.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 13,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/13.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 14,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/14.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 15,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/15.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 16,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/16.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 17,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/17.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 18,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/18.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 19,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/19.gif",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 20,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/20.mp4",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 21,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/21.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 22,
    title: "The Realm of Chaos",
    caption: "The beautiful mess you carry with grace.",
    image: "/assets/images/22.png",
    audio: "/assets/audio/audio1.mp3",
  },
  {
    number: 23,
    message: "Happy 23rd, my universe! 💖🎉",
    image: "/assets/images/23.png",
    audio: "/assets/audio/audio1.mp3",
    isSpecial: true,
  },
];

export default realms;
